name: 0p5.dev
services:
  webapp:
    image: oven/bun:1.3-alpine
    container_name: 0p5.dev
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - "3000:3000"
    tty: true
    entrypoint: ["sh", "-c"]
    command: ["bun install && bun run dev"]
    env_file:
      - .env
    user: "${UID-1000}:${GID-1000}"
